-- Generated by validator.py from the configuration workbook.
-- dialect: postgres, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE load_config_audit (
    audit_id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_audit_sha ON load_config_audit (file_sha256, table_name);

-- Sales!row 2+ - One row per invoice
CREATE TABLE sales (
    sales_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    invoice_no TEXT NOT NULL,
    invoice_date DATE,
    customer TEXT,
    amount NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_sales_row ON sales (file_id, sheet_name, source_row_num);
CREATE INDEX ix_sales_file ON sales (file_id);
CREATE INDEX ix_sales_key ON sales (invoice_no);
COMMENT ON TABLE sales IS '[sales] Invoice-level sales records';
COMMENT ON COLUMN sales.invoice_no IS 'Unique invoice identifier';
COMMENT ON COLUMN sales.invoice_date IS 'Date the invoice was issued';
COMMENT ON COLUMN sales.customer IS 'Customer name';
COMMENT ON COLUMN sales.amount IS 'Invoice total (INR)';

