-- Generated by validator.py from the configuration workbook.
-- dialect: postgres, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Registry of ingested files. Loading the same file twice creates a new
-- file_id, so every staged row stays attributable to one physical load.
CREATE TABLE gf_source_file (
    file_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    row_count        INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_gf_source_file_hash ON gf_source_file (file_sha256);

-- Snapshot of the configuration that produced the tables below.
CREATE TABLE gf_load_config_audit (
    config_id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id          BIGINT NOT NULL REFERENCES gf_source_file (file_id),
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);

-- Summary!row 4+ - Report header: label in col B, value in col C
CREATE TABLE gf_summary (
    summary_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES gf_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    field_label TEXT NOT NULL,
    field_value TEXT
);
CREATE UNIQUE INDEX ux_gf_summary_row ON gf_summary (file_id, sheet_name, source_row_num);
CREATE INDEX ix_gf_summary_file ON gf_summary (file_id);
CREATE INDEX ix_gf_summary_key ON gf_summary (field_label);

-- Payout Breakup!row 4+ - Section/line breakup of the payout
CREATE TABLE gf_payout_breakup (
    payout_breakup_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES gf_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    line_ref TEXT,
    particulars TEXT,
    delivered_orders NUMERIC(18,4),
    cancelled_orders NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_gf_payout_breakup_row ON gf_payout_breakup (file_id, sheet_name, source_row_num);
CREATE INDEX ix_gf_payout_breakup_file ON gf_payout_breakup (file_id);

-- Order Level!row 4+ - One row per order
CREATE TABLE gf_order_level (
    order_level_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES gf_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    serial_no INTEGER,
    order_id TEXT,
    order_date TIMESTAMP,
    restaurant_name TEXT,
    restaurant_id TEXT,
    discount_construct TEXT,
    mode_of_payment TEXT,
    order_status TEXT,
    cancellation_policy TEXT,
    cancellation_reason TEXT,
    cancelled_state TEXT,
    order_type TEXT,
    delivery_state_code TEXT,
    subtotal NUMERIC(18,4),
    packaging_charge NUMERIC(18,4),
    delivery_charge_self_logistics NUMERIC(18,4),
    logistics_charge NUMERIC(18,4),
    restaurant_discount_promo NUMERIC(18,4),
    restaurant_discount_others NUMERIC(18,4),
    brand_pack_subscription_fee NUMERIC(18,4),
    convenience_fee NUMERIC(18,4),
    total_gst_collected NUMERIC(18,4),
    net_order_value NUMERIC(18,4),
    commissionable_value NUMERIC(18,4),
    service_fees_pct NUMERIC(18,4),
    service_fee NUMERIC(18,4),
    payment_mechanism_fee NUMERIC(18,4),
    service_and_payment_fees NUMERIC(18,4),
    taxes_on_service_fees NUMERIC(18,4),
    applicable_amount_tcs NUMERIC(18,4),
    applicable_amount_9_5 NUMERIC(18,4),
    tax_collected_at_source NUMERIC(18,4),
    tcs_igst_amount NUMERIC(18,4),
    tds_194o_amount NUMERIC(18,4),
    gst_paid_by_gf_9_5 NUMERIC(18,4),
    gst_to_be_paid_by_restaurant NUMERIC(18,4),
    government_charges NUMERIC(18,4),
    customer_compensation NUMERIC(18,4),
    delivery_charges_recovery NUMERIC(18,4),
    credit_debit_note_adjustment NUMERIC(18,4),
    promo_recovery_adjustment NUMERIC(18,4),
    extra_inventory_ads_misc NUMERIC(18,4),
    other_order_deductions NUMERIC(18,4),
    net_deductions NUMERIC(18,4),
    net_additions NUMERIC(18,4),
    order_level_payout NUMERIC(18,4),
    buyer_app TEXT,
    settlement_status TEXT,
    settlement_date TIMESTAMP,
    bank_utr TEXT,
    delivery_charge_discount NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_gf_order_level_row ON gf_order_level (file_id, sheet_name, source_row_num);
CREATE INDEX ix_gf_order_level_file ON gf_order_level (file_id);
CREATE INDEX ix_gf_order_level_key ON gf_order_level (order_id);

-- Daywise Completed Breakup!row 3+ - Daywise summary of completed orders
CREATE TABLE gf_daywise_completed (
    daywise_completed_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES gf_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_date DATE,
    number_of_orders INTEGER,
    net_order_value NUMERIC(18,4),
    copay_amount NUMERIC(18,4),
    subtotal NUMERIC(18,4),
    total_packaging_charge NUMERIC(18,4),
    total_gst NUMERIC(18,4),
    service_fee_pct TEXT,
    taxes_on_service_fee_pct TEXT,
    tds NUMERIC(18,4),
    service_fee NUMERIC(18,4),
    taxes_on_service_fee NUMERIC(18,4),
    self_delivery_charges NUMERIC(18,4),
    delivery_discount NUMERIC(18,4),
    total_payable_to_merchant NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_gf_daywise_completed_row ON gf_daywise_completed (file_id, sheet_name, source_row_num);
CREATE INDEX ix_gf_daywise_completed_file ON gf_daywise_completed (file_id);

-- Glossary!row 4+ - Field definitions shipped with the settlement report
CREATE TABLE gf_glossary (
    glossary_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES gf_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    s_no INTEGER,
    particulars TEXT,
    definition TEXT
);
CREATE UNIQUE INDEX ux_gf_glossary_row ON gf_glossary (file_id, sheet_name, source_row_num);
CREATE INDEX ix_gf_glossary_file ON gf_glossary (file_id);
CREATE INDEX ix_gf_glossary_key ON gf_glossary (s_no);

