-- Generated by validator.py from the configuration workbook.
-- dialect: sqlite, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE load_config_audit (
    audit_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TEXT NOT NULL
);
CREATE UNIQUE INDEX ux_audit_sha ON load_config_audit (file_sha256, table_name);

-- Products!row 2+ - showcases all source_ref types + where filter + date_format + column name refs
CREATE TABLE products (
    products_id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    product TEXT NOT NULL,
    category TEXT,
    price NUMERIC,
    qty INTEGER,
    tax_pct NUMERIC,
    discount NUMERIC,
    order_date TEXT,
    currency TEXT,
    warehouse TEXT,
    loaded_at TEXT,
    load_date TEXT,
    row_id TEXT,
    source_file TEXT,
    row_num INTEGER,
    subtotal NUMERIC,
    tax_amount NUMERIC,
    total NUMERIC,
    net_discount NUMERIC,
    neg_discount NUMERIC,
    label TEXT,
    price_label TEXT
);
CREATE UNIQUE INDEX ux_products_row ON products (file_id, sheet_name, source_row_num);
CREATE INDEX ix_products_file ON products (file_id);
CREATE INDEX ix_products_key ON products (product);

