-- Generated by validator.py from the configuration workbook.
-- dialect: sqlite, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE load_config_audit (
    audit_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TEXT NOT NULL
);
CREATE UNIQUE INDEX ux_audit_sha ON load_config_audit (file_sha256, table_name);

-- Types!row 2+ - one column per data type; row 6 is skipped - card is nullable = N and empty
CREATE TABLE card_settlement (
    card_settlement_id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    card TEXT NOT NULL,
    amount NUMERIC,
    qty INTEGER,
    settled_on TEXT,
    settled_at TEXT,
    refunded INTEGER,
    tax_pct NUMERIC
);
CREATE UNIQUE INDEX ux_card_settlement_row ON card_settlement (file_id, sheet_name, source_row_num);
CREATE INDEX ix_card_settlement_file ON card_settlement (file_id);
CREATE INDEX ix_card_settlement_key ON card_settlement (card);

