-- Generated by validator.py from the configuration workbook.
-- dialect: sqlite, id_type: uuid. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE load_config_audit (
    audit_id         TEXT PRIMARY KEY,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TEXT NOT NULL
);
CREATE UNIQUE INDEX ux_audit_sha ON load_config_audit (file_sha256, table_name);

-- Orders!row 2+ - id_type = uuid, so orders_id and file_id are UUIDs
CREATE TABLE orders (
    orders_id TEXT PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id_ext TEXT NOT NULL,
    placed_on TEXT,
    restaurant TEXT,
    total NUMERIC
);
CREATE UNIQUE INDEX ux_orders_row ON orders (file_id, sheet_name, source_row_num);
CREATE INDEX ix_orders_file ON orders (file_id);
CREATE INDEX ix_orders_key ON orders (order_id_ext);

