-- Generated by validator.py from the configuration workbook.
-- dialect: postgres, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE load_config_audit (
    audit_id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_audit_sha ON load_config_audit (file_sha256, table_name);

-- Header!row 3+ - Label/value pairs; title on row 1 is outside the range
CREATE TABLE report_header (
    report_header_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    field_label TEXT NOT NULL,
    field_value TEXT
);
CREATE UNIQUE INDEX ux_report_header_row ON report_header (file_id, sheet_name, source_row_num);
CREATE INDEX ix_report_header_file ON report_header (file_id);
CREATE INDEX ix_report_header_key ON report_header (field_label);

-- Payments!row 4+ - First block on the sheet
CREATE TABLE payments_card (
    payments_card_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    card_type TEXT NOT NULL,
    txn_count INTEGER,
    amount NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_payments_card_row ON payments_card (file_id, sheet_name, source_row_num);
CREATE INDEX ix_payments_card_file ON payments_card (file_id);
CREATE INDEX ix_payments_card_key ON payments_card (card_type);

-- Payments!row 10+ - Second block on the same sheet = its own table
CREATE TABLE payments_cash (
    payments_cash_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    denomination INTEGER NOT NULL,
    note_count INTEGER,
    amount NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_payments_cash_row ON payments_cash (file_id, sheet_name, source_row_num);
CREATE INDEX ix_payments_cash_file ON payments_cash (file_id);
CREATE INDEX ix_payments_cash_key ON payments_cash (denomination);

-- Items!row 2+ - Ends at row 6 so the TOTAL row on row 7 is not loaded
CREATE TABLE items (
    items_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    item_code TEXT NOT NULL,
    item_name TEXT,
    qty INTEGER,
    gross_amount NUMERIC(18,4),
    tax_pct NUMERIC(18,4),
    sold_on DATE
);
CREATE UNIQUE INDEX ux_items_row ON items (file_id, sheet_name, source_row_num);
CREATE INDEX ix_items_file ON items (file_id);
CREATE INDEX ix_items_key ON items (item_code);

