-- Generated by validator.py from the configuration workbook.
-- dialect: postgres, id_type: uuid. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE ks_load_config_audit (
    audit_id         UUID PRIMARY KEY,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_ks_audit_sha ON ks_load_config_audit (file_sha256, table_name);

-- Orders!row 2+ - where filters out Cancelled orders
CREATE TABLE ks_orders (
    orders_id UUID PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT NOT NULL,
    customer TEXT NOT NULL,
    order_date DATE,
    status TEXT NOT NULL,
    subtotal NUMERIC(18,4),
    tax_pct NUMERIC(18,4),
    discount NUMERIC(18,4),
    is_paid BOOLEAN,
    notes TEXT,
    loaded_at TIMESTAMP,
    load_date DATE,
    row_uuid TEXT,
    source_file TEXT,
    row_num INTEGER,
    currency TEXT,
    api_version TEXT,
    tax_amount NUMERIC(18,4),
    gross_total NUMERIC(18,4),
    net_total NUMERIC(18,4),
    neg_discount NUMERIC(18,4),
    surcharge_1pct NUMERIC(18,4),
    order_label TEXT,
    id_with_date TEXT,
    order_month DATE
);
CREATE UNIQUE INDEX ux_ks_orders_row ON ks_orders (file_id, sheet_name, source_row_num);
CREATE INDEX ix_ks_orders_file ON ks_orders (file_id);
CREATE INDEX ix_ks_orders_key ON ks_orders (order_id);
COMMENT ON TABLE ks_orders IS '[sales] Customer orders, filtered to Active only';
COMMENT ON COLUMN ks_orders.order_id IS 'unique order identifier';
COMMENT ON COLUMN ks_orders.customer IS 'customer name, cleaned';
COMMENT ON COLUMN ks_orders.order_date IS 'pinned to MM/DD/YYYY';
COMMENT ON COLUMN ks_orders.status IS 'active/cancelled';
COMMENT ON COLUMN ks_orders.subtotal IS 'handles ₹, commas, (neg) (INR)';
COMMENT ON COLUMN ks_orders.tax_pct IS 'tax percentage (percent)';
COMMENT ON COLUMN ks_orders.discount IS 'NULL -> 0 via null_default (INR)';
COMMENT ON COLUMN ks_orders.is_paid IS 'yes/no/true/false/1/0';
COMMENT ON COLUMN ks_orders.notes IS 'null_default = N/A';
COMMENT ON COLUMN ks_orders.loaded_at IS 'fn:now — load timestamp';
COMMENT ON COLUMN ks_orders.load_date IS 'fn:today — load date';
COMMENT ON COLUMN ks_orders.row_uuid IS 'fn:uuid — unique per row';
COMMENT ON COLUMN ks_orders.source_file IS 'fn:file_name';
COMMENT ON COLUMN ks_orders.row_num IS 'fn:sequence — 1,2,3...';
COMMENT ON COLUMN ks_orders.currency IS 'const: fixed value';
COMMENT ON COLUMN ks_orders.api_version IS 'const: another constant';
COMMENT ON COLUMN ks_orders.tax_amount IS 'column name refs + round_2 (INR)';
COMMENT ON COLUMN ks_orders.gross_total IS 'column name refs (INR)';
COMMENT ON COLUMN ks_orders.net_total IS 'NULL propagation if discount NULL (but null_default=0) (INR)';
COMMENT ON COLUMN ks_orders.neg_discount IS 'unary minus (INR)';
COMMENT ON COLUMN ks_orders.surcharge_1pct IS 'parentheses + literal (INR)';
COMMENT ON COLUMN ks_orders.order_label IS 'string concat with &';
COMMENT ON COLUMN ks_orders.id_with_date IS 'mix col + fn in expr';
COMMENT ON COLUMN ks_orders.order_month IS 'date cast + year_month script';

-- Items!row 2+ - FK to orders via order_id
CREATE TABLE ks_items (
    items_id UUID PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT NOT NULL,
    item_name TEXT NOT NULL,
    qty INTEGER,
    unit_price NUMERIC(18,4) NOT NULL,
    item_date DATE,
    line_total NUMERIC(18,4),
    line_num INTEGER,
    unit TEXT
);
CREATE UNIQUE INDEX ux_ks_items_row ON ks_items (file_id, sheet_name, source_row_num);
CREATE INDEX ix_ks_items_file ON ks_items (file_id);
CREATE INDEX ix_ks_items_key ON ks_items (order_id);
COMMENT ON TABLE ks_items IS '[sales] Line items for each order';
COMMENT ON COLUMN ks_items.order_id IS 'FK to orders table';
COMMENT ON COLUMN ks_items.item_name IS 'item description';
COMMENT ON COLUMN ks_items.qty IS 'null_default=0, clamped';
COMMENT ON COLUMN ks_items.unit_price IS 'price per unit (INR)';
COMMENT ON COLUMN ks_items.item_date IS 'DD-Mon-YYYY format';
COMMENT ON COLUMN ks_items.line_total IS 'computed from col names (INR)';
COMMENT ON COLUMN ks_items.line_num IS 'sequence per table';
COMMENT ON COLUMN ks_items.unit IS 'const: unit of measure';

-- Summary!row 1+ - key_value layout — no header row
CREATE TABLE ks_summary (
    summary_id UUID PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    label TEXT NOT NULL,
    value TEXT,
    captured_at TIMESTAMP
);
CREATE UNIQUE INDEX ux_ks_summary_row ON ks_summary (file_id, sheet_name, source_row_num);
CREATE INDEX ix_ks_summary_file ON ks_summary (file_id);
COMMENT ON TABLE ks_summary IS '[meta] Report metadata in key-value format';
COMMENT ON COLUMN ks_summary.label IS 'the key/label';
COMMENT ON COLUMN ks_summary.value IS 'the value, kept as text';
COMMENT ON COLUMN ks_summary.captured_at IS 'when this was loaded';

