-- Generated by validator.py from the configuration workbook.
-- dialect: postgres, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Registry of ingested files. Loading the same file twice creates a new
-- file_id, so every staged row stays attributable to one physical load.
CREATE TABLE swiggy_source_file (
    file_id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    row_count        INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_swiggy_source_file_hash ON swiggy_source_file (file_sha256);

-- Snapshot of the configuration that produced the tables below.
CREATE TABLE swiggy_load_config_audit (
    config_id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id          BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);

-- Summary!row 12+ - Payout header: label in col B, value in col C
CREATE TABLE swiggy_summary (
    summary_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    field_label TEXT NOT NULL,
    field_value TEXT NOT NULL
);
CREATE UNIQUE INDEX ux_swiggy_summary_row ON swiggy_summary (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_summary_file ON swiggy_summary (file_id);
CREATE INDEX ix_swiggy_summary_key ON swiggy_summary (field_label);

-- Payout Breakup!row 7+ - Section/line breakup of the payout
CREATE TABLE swiggy_payout_breakup (
    payout_breakup_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    line_ref TEXT,
    particulars TEXT,
    swiggy_delivered NUMERIC(18,4),
    swiggy_cancelled NUMERIC(18,4),
    toing_delivered NUMERIC(18,4),
    toing_cancelled NUMERIC(18,4),
    total_amount NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_swiggy_payout_breakup_row ON swiggy_payout_breakup (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_payout_breakup_file ON swiggy_payout_breakup (file_id);

-- Order Level!row 4+ - One row per order
CREATE TABLE swiggy_order_level (
    order_level_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT,
    parent_order_id TEXT,
    order_date TIMESTAMP,
    order_status TEXT,
    order_category TEXT,
    order_payment_type TEXT,
    cancelled_by TEXT,
    coupon_type_applied_by_customer TEXT,
    item_total NUMERIC(18,4),
    packaging_charges NUMERIC(18,4),
    restaurant_discounts NUMERIC(18,4),
    swiggy_one_exclusive_offer_discount NUMERIC(18,4),
    restaurant_discount_share NUMERIC(18,4),
    net_bill_value NUMERIC(18,4),
    gst_collected NUMERIC(18,4),
    total_customer_paid NUMERIC(18,4),
    commission_charged_on NUMERIC(18,4),
    service_fees_pct NUMERIC(18,4),
    commission NUMERIC(18,4),
    long_distance_charges NUMERIC(18,4),
    discount_on_long_distance_fee NUMERIC(18,4),
    pocket_hero_fees NUMERIC(18,4),
    no_fees_week_cashback NUMERIC(18,4),
    swiggy_one_fees NUMERIC(18,4),
    payment_collection_charges NUMERIC(18,4),
    restaurant_cancellation_charges NUMERIC(18,4),
    call_center_charges NUMERIC(18,4),
    delivery_fee_sponsored_by_restaurant NUMERIC(18,4),
    bolt_fees NUMERIC(18,4),
    gst_on_service_fee_18_pct NUMERIC(18,4),
    total_swiggy_fees NUMERIC(18,4),
    customer_cancellations NUMERIC(18,4),
    customer_complaints NUMERIC(18,4),
    complaint_and_cancellation_charges NUMERIC(18,4),
    gst_deduction NUMERIC(18,4),
    tcs NUMERIC(18,4),
    tds NUMERIC(18,4),
    total_taxes NUMERIC(18,4),
    net_payout_for_order NUMERIC(18,4),
    long_distance_order TEXT,
    last_mile_km NUMERIC(18,4),
    mfr_accurate TEXT,
    mfr_pressed TEXT,
    coupon_code_sourced TEXT,
    discount_campaign_id TEXT,
    replicated_order TEXT,
    base_order_id TEXT,
    cancellation_time NUMERIC(18,4),
    pick_up_status TEXT,
    swiggy_one_customer TEXT,
    pocket_hero_order TEXT
);
CREATE UNIQUE INDEX ux_swiggy_order_level_row ON swiggy_order_level (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_order_level_file ON swiggy_order_level (file_id);
CREATE INDEX ix_swiggy_order_level_key ON swiggy_order_level (order_id);
COMMENT ON TABLE swiggy_order_level IS '[food_delivery] Order-level charges and payouts from Swiggy';

-- Unresolved Customer Complaints!row 2+ - Processed / not-processed order counts
CREATE TABLE swiggy_complaint_status (
    complaint_status_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    payout_period TEXT,
    order_type TEXT,
    status TEXT,
    no_of_orders NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_swiggy_complaint_status_row ON swiggy_complaint_status (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_complaint_status_file ON swiggy_complaint_status (file_id);

-- Unresolved Customer Complaints!row 22+ - Order level detail of unresolved complaints
CREATE TABLE swiggy_complaint_orders (
    complaint_orders_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_date TIMESTAMP,
    order_id TEXT,
    order_status TEXT,
    order_category TEXT,
    item_total NUMERIC(18,4),
    packaging_charges NUMERIC(18,4),
    restaurant_discounts NUMERIC(18,4),
    swiggy_one_exclusive_offer_discount NUMERIC(18,4),
    restaurant_discount_share NUMERIC(18,4),
    net_bill_value NUMERIC(18,4),
    gst_collected NUMERIC(18,4),
    total_customer_paid NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_swiggy_complaint_orders_row ON swiggy_complaint_orders (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_complaint_orders_file ON swiggy_complaint_orders (file_id);
CREATE INDEX ix_swiggy_complaint_orders_key ON swiggy_complaint_orders (order_id);

-- Growth Investments and Other De!row 12+ - Restaurant adjustments, this week block
CREATE TABLE swiggy_adjustments_current (
    adjustments_current_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    adjustment_type TEXT,
    total_amount NUMERIC(18,4),
    settled_amount NUMERIC(18,4),
    outstanding_amount NUMERIC(18,4),
    period_from DATE,
    period_to DATE,
    invoice_number TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_adjustments_current_row ON swiggy_adjustments_current (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_adjustments_current_file ON swiggy_adjustments_current (file_id);

-- Growth Investments and Other De!row 16+ - Restaurant adjustments, previous weeks block
CREATE TABLE swiggy_adjustments_previous (
    adjustments_previous_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    adjustment_type TEXT,
    total_amount NUMERIC(18,4),
    settled_amount NUMERIC(18,4),
    outstanding_amount NUMERIC(18,4),
    period_from DATE,
    period_to DATE,
    invoice_number TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_adjustments_previous_row ON swiggy_adjustments_previous (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_adjustments_previous_file ON swiggy_adjustments_previous (file_id);

-- Growth Investments and Other De!row 31+ - Ads investments this week; Invoice Number/Remarks headers sit on row 30
CREATE TABLE swiggy_ads_investments_current (
    ads_investments_current_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    adjustment_type TEXT,
    campaign_start_date DATE,
    campaign_end_date DATE,
    total_amount NUMERIC(18,4),
    settled_amount NUMERIC(18,4),
    outstanding_amount NUMERIC(18,4),
    period_from DATE,
    period_to DATE,
    invoice_number TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_ads_investments_current_row ON swiggy_ads_investments_current (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_ads_investments_current_file ON swiggy_ads_investments_current (file_id);

-- Growth Investments and Other De!row 35+ - Ads investments, previous weeks block
CREATE TABLE swiggy_ads_investments_previous (
    ads_investments_previous_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    adjustment_type TEXT,
    campaign_start_date DATE,
    campaign_end_date DATE,
    total_amount NUMERIC(18,4),
    settled_amount NUMERIC(18,4),
    outstanding_amount NUMERIC(18,4),
    period_from DATE,
    period_to DATE,
    invoice_number TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_ads_investments_previous_row ON swiggy_ads_investments_previous (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_ads_investments_previous_file ON swiggy_ads_investments_previous (file_id);

-- Growth Investments and Other De!row 47+ - Recovery details
CREATE TABLE swiggy_recoveries (
    recoveries_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    recovery_outlet TEXT,
    period_from DATE,
    period_to DATE,
    recovered_amount NUMERIC(18,4),
    invoice_number TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_recoveries_row ON swiggy_recoveries (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_recoveries_file ON swiggy_recoveries (file_id);

-- Discount Summary!row 4+ - Swiggy discount block
CREATE TABLE swiggy_discount_summary_swiggy (
    discount_summary_swiggy_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    validity TEXT,
    coupon_details TEXT,
    restaurant_share_pct NUMERIC(18,4),
    total_orders NUMERIC(18,4),
    total_discount_given NUMERIC(18,4),
    target_customers TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_discount_summary_swiggy_row ON swiggy_discount_summary_swiggy (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_discount_summary_swiggy_file ON swiggy_discount_summary_swiggy (file_id);

-- Discount Summary!row 19+ - Toing discount block
CREATE TABLE swiggy_discount_summary_toing (
    discount_summary_toing_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    validity TEXT,
    coupon_details TEXT,
    restaurant_share_pct NUMERIC(18,4),
    total_orders NUMERIC(18,4),
    total_discount_given NUMERIC(18,4),
    target_customers TEXT,
    remarks TEXT
);
CREATE UNIQUE INDEX ux_swiggy_discount_summary_toing_row ON swiggy_discount_summary_toing (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_discount_summary_toing_file ON swiggy_discount_summary_toing (file_id);

-- Glossary!row 3+ - Field definitions shipped with the annexure
CREATE TABLE swiggy_glossary (
    glossary_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL REFERENCES swiggy_source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    s_no NUMERIC(18,4),
    particulars TEXT,
    definition TEXT
);
CREATE UNIQUE INDEX ux_swiggy_glossary_row ON swiggy_glossary (file_id, sheet_name, source_row_num);
CREATE INDEX ix_swiggy_glossary_file ON swiggy_glossary (file_id);
CREATE INDEX ix_swiggy_glossary_key ON swiggy_glossary (s_no);

