-- Generated by validator.py from the configuration workbook.
-- dialect: sqlite, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Registry of ingested files. Loading the same file twice creates a new
-- file_id, so every staged row stays attributable to one physical load.
CREATE TABLE source_file (
    file_id          INTEGER PRIMARY KEY AUTOINCREMENT,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    restaurant_id    TEXT,
    restaurant_name  TEXT,
    gstin            TEXT,
    payout_period    TEXT,
    settlement_date  TEXT,
    row_count        INTEGER,
    loaded_at        TEXT NOT NULL
);
CREATE UNIQUE INDEX ux_source_file_hash ON source_file (file_sha256);

-- Snapshot of the configuration that produced the tables below.
CREATE TABLE load_config_audit (
    config_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id          INTEGER NOT NULL REFERENCES source_file (file_id),
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    loaded_at        TEXT NOT NULL
);

-- Orders!row 2+ - One row per order
CREATE TABLE orders (
    orders_id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL REFERENCES source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT NOT NULL,
    order_date TEXT,
    customer TEXT,
    total NUMERIC
);
CREATE UNIQUE INDEX ux_orders_row ON orders (file_id, sheet_name, source_row_num);
CREATE INDEX ix_orders_file ON orders (file_id);
CREATE INDEX ix_orders_key ON orders (order_id);

-- Items!row 2+ - One row per line item
CREATE TABLE items (
    items_id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_id INTEGER NOT NULL REFERENCES source_file (file_id),
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT NOT NULL,
    item_code TEXT NOT NULL,
    item_name TEXT,
    qty INTEGER,
    unit_price NUMERIC,
    amount NUMERIC
);
CREATE UNIQUE INDEX ux_items_row ON items (file_id, sheet_name, source_row_num);
CREATE INDEX ix_items_file ON items (file_id);
CREATE INDEX ix_items_key ON items (order_id, item_code);

