-- Generated by validator.py from the configuration workbook.
-- dialect: postgres, id_type: integer. Do not edit by hand; change the config and regenerate.

-- Audit of every load: which file was loaded, with which config, into which table.
-- file_sha256 is unique so re-loading identical content is refused.
CREATE TABLE load_config_audit (
    audit_id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id          TEXT NOT NULL,
    file_name        TEXT NOT NULL,
    file_sha256      TEXT NOT NULL,
    source_ref       TEXT,
    config_ref       TEXT,
    table_name       TEXT NOT NULL,
    sheet_name       TEXT NOT NULL,
    header_row       INTEGER,
    data_start_row   INTEGER,
    data_end_row     INTEGER,
    column_count     INTEGER,
    row_count        INTEGER,
    loaded_at        TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ux_audit_sha ON load_config_audit (file_sha256, table_name);

-- Orders!row 2+ - One row per order
CREATE TABLE orders (
    orders_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT NOT NULL,
    order_date DATE,
    customer TEXT,
    total NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_orders_row ON orders (file_id, sheet_name, source_row_num);
CREATE INDEX ix_orders_file ON orders (file_id);
CREATE INDEX ix_orders_key ON orders (order_id);
COMMENT ON TABLE orders IS '[sales] Order headers with foreign key references';

-- Items!row 2+ - One row per line item
CREATE TABLE items (
    items_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    file_id TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_sha256 TEXT NOT NULL,
    source_ref TEXT,
    sheet_name TEXT NOT NULL,
    source_row_num INTEGER NOT NULL,
    order_id TEXT NOT NULL,
    item_code TEXT NOT NULL,
    item_name TEXT,
    qty INTEGER,
    unit_price NUMERIC(18,4),
    amount NUMERIC(18,4)
);
CREATE UNIQUE INDEX ux_items_row ON items (file_id, sheet_name, source_row_num);
CREATE INDEX ix_items_file ON items (file_id);
CREATE INDEX ix_items_key ON items (order_id, item_code);
COMMENT ON TABLE items IS '[sales] Order line items referencing orders';

